application: magi-metrics-python-example
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /reporting-api/.*
  script: reporting-api.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "latest"

